# Generated by Django 4.1.7 on 2023-03-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('active', models.BooleanField()),
                ('tags', models.TextField(blank=True)),
                ('picture', models.TextField(blank=True)),
            ],
        ),
    ]
